### PR TITLE
Integrate fix/ajax-requests into develop

### LINKED ISSUE #186: add language parameter to AJAX calls
As with the editionId always being submitted in AJAX calls it would be good to also generally submit the current application language as AJAX parameter. (AJAXController.js)

### PR DESCRIPTION
**Pull request by roewenstrunk**
This PR is related to #185 and #186 

closes #186

### CODE REVIEW

**Review by bwbohl — CHANGES_REQUESTED** [review]
After testing a clean build and a build after merging to develop I still get the following error loading the Edirom Online:

```
app.js:51852 Uncaught TypeError: Cannot read properties of undefined (reading 'data/xql/getEditionURI.xql')
    at constructor.getPreference (app.js:51852:22)
    at method (app.js:3269:17)
    at constructor.doAJAXRequest (app.js:51786:25)
    at method (app.js:3269:17)
    at constructor.launch (app.js:56922:10)
    at constructor.onBeforeLaunch (app.js:31602:13)
    at constructor (app.js:31563:6)
    at new constructor (app.js:4677:31)
    at app.js:6485:36
    at app.js:7450:22
getPreference @ app.js:51852
method @ app.js:3269
doAJAXRequest @ app.js:51786
method @ app.js:3269
launch @ app.js:56922
onBeforeLaunch @ app.js:31602
constructor @ app.js:31563
constructor @ app.js:4677
(anonymous) @ app.js:6485
(anonymous) @ app.js:7450
fire @ app.js:7417
readyEvent.fire @ app.js:7574
fireReadyEvent @ app.js:7620
(anonymous) @ app.js:3284
setTimeout (async)
defer @ app.js:3333
fireDocReady @ app.js:7610
onReadyEvent @ app.js:7600
```

Apparently something is going wrong, ~~might be the return type of getEditionURI.xql~~.[EDIT]

**Comment by bwbohl** [comment]
Can #104 also be considered fixed with this PR?

File: app/controller/PreferenceController.js [hunk 1]
```diff
@@ -30,18 +30,18 @@ Ext.define('EdiromOnline.controller.PreferenceController', {
...
             },
-            scope: this
-        });
+            Ext.bind(function(response){
+                this.setPreferences(Ext.JSON.decode(response.responseText));
+            }, this),
+            2, // retries
+            false // async
+        );
     },
```
Comment (bwbohl) [inline app/controller/PreferenceController.js:45]: The Edirom Online fails with

```
app.js:51858 Uncaught TypeError: Cannot read properties of undefined (reading 'data/xql/getPreferences.xql'
```

unless this stays the old way or the override check is removed from the AJAXController

**Review by bwbohl — CHANGES_REQUESTED** [review]
Either we remove the override possibility from the AJAXController OR we stick to the old Ext.Ajax.request for initializing the preferences OR we somehow avoid that when getPreferences.xql is called.

**Comment by bwbohl** [comment]
After that is fixed it still fails, when tryinig to `getPreference` as long as the preferences aren't available yet.

This might fix it:
```js
    getPreference: function (key, lax) {
        var me = this;

        (async () => {
            console.log("waiting for preferences");
            while (me.preferences === undefined) // define the condition as you like
            await new Promise(resolve => setTimeout(resolve, 1000));
            console.log("preferences defined");
            if (! me.preferences[key] && lax) {
                return null;
            }
            if (key == 'application_language') {
                var lang = me.getURLParameter('lang');
                if (lang) {
                    return lang;
                } else {
                    return 'en';
                }
            }
            if (me.preferences[key] == '' && key == 'image_prefix') {
                return '';
            }
            if (! me.preferences[key]) {
                Ext.Error.raise({
                    msg: 'No preference found with this key', key: key, level: 'warn'
                });
                return null;
            }
            return me.preferences[key];
        })();
    }
```

**Comment by bwbohl** [comment]
After that the language problem kicks in for getLanguageString…

so maybe we should test with a merged #308 ?

**Comment by bwbohl** [comment]
pinging @roewenstrunk

**Comment by bwbohl** [comment]
pinging @roewenstrunk

**Comment by bwbohl** [comment]
Attempt to boil it down to some understandable language:

1. When Edirom-Online loads without any further parameter in the call, it does not know the active edition and thus does not know where to find the edition preferences.
2. The AJAXController has an override variable that comes from the old plugin mechanism. The idea was that for any JS or XQuery file in the Edirom-Online code a custom file could be injected by defining the file path of the replaced file as preference `@key` and supplying the path to the injected file as value, e.g.:
   ```xml
   <entry key="plugin_annotView" value="../../../exist/rest/db/$CONTENTS_FOLDER$/$EDITION_ID$/$ANY_PATH$/$FILE_NAME$.js"/>
 ```
 3. This results in a check for a 'plugin' when trying to load the preferences, which cannot succeed because the definition of a plugin would be in the preferences and of course injecting another preferences file this way would be complete nonsense.

Theoretically, possible solutions could be to:

1. Avoid override check when fetching preferences
2. Catching an error on the override variable when trying to fetch an override defined in the preferences fails
3. getting rid of the Plug-In mechanism which actually isn't state of the art – relying on rest – and might pose major security concerns.

**Review by bwbohl — APPROVED** [review]

File: app/controller/PreferenceController.js (hunk 1 above)
Comment (bwbohl) [reply app/controller/PreferenceController.js:45]: added an override exclusion mechanism
